version: "3"
services:
  client:
    build: ./client
    restart: always
    ports:
      - "80:3000"
  
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: tiktak
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"